
spring:
  application:
    name: centralized-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahul-ghadge/properties-repository.git

server:
  port: 8888
